### ISSUE TITLE
classes for \033[1;31m -- should they be -Color -Color-Bold -Color-Red?

### ISSUE THREAD

**Issue by asottile** [chriskuehl/pygments-ansi-color#9]
currently this produces `-Color -Color-Bold -Color-Bold-Red`, requiring a bit more CSS than I'd like

**Comment by asottile** [comment]
hmmm interestingly this seems to work on fluffy, and I'm not sure why: https://i.fluffy.cc/BDj1NHzzsdhJlpKstVw0qnm4Lq2mM5w9.html

**Comment by chriskuehl** [comment]
If I remember correctly, I think it's because Pygments generates CSS classes for a tokens such as `Token.A.B.C` as `A`, `A-B`, `A-B-C` without any way to tell it "what I really want is `A`, `B`, `C`". That's why when enabling 256-color mode it's required to use this mixin which patches the class generation logic to generate like you're suggesting:
https://github.com/chriskuehl/pygments-ansi-color/blob/2a8c1f61d938888b60f49abce4dad1a61be628a4/pygments_ansi_color.py#L268-L277

Also some details in the README though not sure if they 100% apply: 
https://github.com/chriskuehl/pygments-ansi-color#optional-enable-256-color-support

**Comment by asottile** [comment]
ahhh so if I use the 256color patch it'll work, cool
